/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.locify.client.gui;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class raw {
        public static final int add=0x7f030000;
        public static final int addfromlink=0x7f030001;
        public static final int addfromlist=0x7f030002;
        public static final int address=0x7f030003;
        public static final int arial_10_black=0x7f030004;
        public static final int arial_10_white=0x7f030005;
        public static final int arial_14_black=0x7f030006;
        public static final int arial_14_white=0x7f030007;
        public static final int arial_16_black=0x7f030008;
        public static final int arial_16_white=0x7f030009;
        public static final int arial_18_black=0x7f03000a;
        public static final int arial_18_white_big_bold_letters_only=0x7f03000b;
        public static final int broken=0x7f03000c;
        public static final int browse=0x7f03000d;
        public static final int checkbox=0x7f03000e;
        public static final int checkbox_checked=0x7f03000f;
        public static final int checkversion=0x7f030010;
        public static final int compass=0x7f030011;
        public static final int connecting_21x21=0x7f030012;
        public static final int connecting_animation_21x21=0x7f030013;
        public static final int coordinates=0x7f030014;
        public static final int corruptedfile=0x7f030015;
        public static final int cs_cz=0x7f030016;
        public static final int delete=0x7f030017;
        public static final int en=0x7f030018;
        public static final int exit=0x7f030019;
        public static final int gps=0x7f03001a;
        public static final int help=0x7f03001b;
        public static final int home=0x7f03001c;
        public static final int icon=0x7f03001d;
        public static final int lastknown=0x7f03001e;
        public static final int left=0x7f03001f;
        public static final int loading=0x7f030020;
        public static final int manage=0x7f030021;
        public static final int manual=0x7f030022;
        public static final int map_icon_actualloc=0x7f030023;
        public static final int map_icon_minus=0x7f030024;
        public static final int map_icon_plus=0x7f030025;
        public static final int map_icon_zoom_minus=0x7f030026;
        public static final int map_icon_zoom_plus=0x7f030027;
        public static final int map_point_orange_21x21=0x7f030028;
        public static final int map_tile_64x64=0x7f030029;
        public static final int maps=0x7f03002a;
        public static final int more=0x7f03002b;
        public static final int more5=0x7f03002c;
        public static final int moreinfo=0x7f03002d;
        public static final int move=0x7f03002e;
        public static final int multisymbol=0x7f03002f;
        public static final int navigatealong=0x7f030030;
        public static final int navigateto=0x7f030031;
        public static final int navigation=0x7f030032;
        public static final int nmeatest1=0x7f030033;
        public static final int nmeatest2=0x7f030034;
        public static final int number000=0x7f030035;
        public static final int number030=0x7f030036;
        public static final int number060=0x7f030037;
        public static final int number090=0x7f030038;
        public static final int number120=0x7f030039;
        public static final int number150=0x7f03003a;
        public static final int number180=0x7f03003b;
        public static final int number210=0x7f03003c;
        public static final int number240=0x7f03003d;
        public static final int number270=0x7f03003e;
        public static final int number300=0x7f03003f;
        public static final int number330=0x7f030040;
        public static final int numbere=0x7f030041;
        public static final int numbern=0x7f030042;
        public static final int numbers=0x7f030043;
        public static final int numberw=0x7f030044;
        public static final int online=0x7f030045;
        public static final int popup=0x7f030046;
        public static final int radio=0x7f030047;
        public static final int radio_selected=0x7f030048;
        public static final int receiving_21x21=0x7f030049;
        public static final int recordroute=0x7f03004a;
        public static final int renameservice=0x7f03004b;
        public static final int right=0x7f03004c;
        public static final int routesymbol=0x7f03004d;
        public static final int saved=0x7f03004e;
        public static final int savedlocation=0x7f03004f;
        public static final int saveplace=0x7f030050;
        public static final int select=0x7f030051;
        public static final int sending_21x21=0x7f030052;
        public static final int servicesettings=0x7f030053;
        public static final int settings=0x7f030054;
        public static final int shortcut_to_download_25x25=0x7f030055;
        public static final int state_pause_21x21=0x7f030056;
        public static final int state_recording_21x21=0x7f030057;
        public static final int status_animation=0x7f030058;
        public static final int status_connecting=0x7f030059;
        public static final int status_normal=0x7f03005a;
        public static final int status_nosignal=0x7f03005b;
        public static final int status_strong=0x7f03005c;
        public static final int status_weak=0x7f03005d;
        public static final int text=0x7f03005e;
        public static final int updateservice=0x7f03005f;
        public static final int viewlocation=0x7f030060;
        public static final int viewplace=0x7f030061;
        public static final int viewroute=0x7f030062;
        public static final int waypointcloudsymbol=0x7f030063;
        public static final int waypointsymbol=0x7f030064;
        public static final int where=0x7f030065;
        public static final int wpt_description_01=0x7f030066;
        public static final int wpt_description_02=0x7f030067;
        public static final int wpt_description_03=0x7f030068;
        public static final int wpt_description_background=0x7f030069;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
